### Signup
POST {{baseUrl}}/auth/signup

{
"username" : "soroush2",
"password" : "222"
}

### Login

POST {{baseUrl}}/auth/login
Accept: application/json

{
"username"  : "soroush2",
"password" : "222"
}

