### Signup
POST {{baseUrl}}/auth/signup

{
"username" : "soroush3",
"password" : "222",
"email" : "sorooshjaberi@gmail.com"
}

### Login

POST {{baseUrl}}/auth/login
Accept: application/json

{
"username"  : "soroush2",
"password" : "222"
}

