### Create a new todo

POST {{baseUrl}}/todos
Authorization: Bearer {{access_token}}

{
"title" : "Test4",
"description" : "THis is test4"
}

### Get all todos

GET {{baseUrl}}/todos
Authorization: Bearer {{access_token}}

### Get a todo

GET {{baseUrl}}/todos/1
Authorization: Bearer {{access_token}}

### Edit a todo

PUT {{baseUrl}}/todos/10
Authorization: Bearer {{access_token}}

{
 "done" : true,
 "title" : "Soroush"
}

### Delete a todo

DELETE {{baseUrl}}/todos/8
Authorization: Bearer {{access_token}}

